apiVersion: v1
kind: Service
metadata:
  name: ts-scratch
  labels:
    app: ts-scratch
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: port0
  selector:
    app: ts-scratch
  type: NodePort
  sessionAffinity: None
